name: alpha_twelve
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.6.1
  equatable: ^2.0.7
  shared_preferences: ^2.3.3
  hugeicons: ^0.0.11
  flutter_svg: ^2.0.17
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_gen_runner: ^4.0.0
  flutter_svg_opt: ^0.0.1
  build_runner: ^2.4.6

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - fonts/
    - assets/products.json


  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/SFPRODISPLAYBLACKITALIC.OTF
        - asset: fonts/SFPRODISPLAYBOLD.OTF
        - asset: fonts/SFPRODISPLAYHEAVYITALIC.OTF
        - asset: fonts/SFPRODISPLAYLIGHTITALIC.OTF
        - asset: fonts/SFPRODISPLAYMEDIUM.OTF
        - asset: fonts/SFPRODISPLAYREGULAR.OTF
        - asset: fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
        - asset: fonts/SFPRODISPLAYTHINITALIC.OTF
        - asset: fonts/SFPRODISPLAYULTRALIGHTITALIC.OTF